Numpy Notes

In [3]:
import numpy as np 

The Basics 

In [11]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [12]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [13]:
#Get Dimension 
a.ndim

1

In [14]:
#Get Shape
b.shape

(2, 3)

In [15]:
#Get Type 
a.dtype

dtype('int32')

In [16]:
#Get Size 
a.itemsize

4

In [17]:
#Get total size 
a.nbytes

12

Accessing/Changing specific elements, rows, columns etc

In [18]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
#Get a specific element [r, c]
a[1, 5]

13

In [20]:
#Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
#Get a specific column 
a[:, 2]

array([ 3, 10])

In [23]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

Array Creation 

In [25]:
#Any Number 
np.full((2,3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [26]:
#Random decimal numbers 
np.random.rand(4,2)

array([[0.06673298, 0.9335913 ],
       [0.68119639, 0.63062509],
       [0.91279362, 0.41111565],
       [0.20114789, 0.41023844]])

In [27]:
#Random integer values 
np.random.randint(7, size=(3,3))

array([[0, 6, 3],
       [1, 0, 0],
       [4, 6, 6]])

In [28]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [33]:
output = np.ones((5,5))
print(output)

z = np.zeros((3, 3))
z[1,1] = 9
print(z)

output[1:-1, 1:-1] = z 
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying arrays! 

In [35]:
a = np.array([1,2,3])
#you must use .copy to specify that you are making a copy or else whatever new values you assign to be will also be 
#assigned to a 
b = a.copy()
b[0] = 100 
print(b)

[100   2   3]


Mathematics

In [36]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [37]:
a + 2

array([3, 4, 5, 6])

In [38]:
a - 2

array([-1,  0,  1,  2])

In [39]:
a * 2

array([2, 4, 6, 8])

In [40]:
a / 2 

array([0.5, 1. , 1.5, 2. ])

In [41]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [42]:
a ** 2

array([ 1,  4,  9, 16])

Statistics

In [43]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
np.min(stats)

1

In [45]:
np.max(stats, axis=1)

array([3, 6])

In [46]:
#Adds up all values in the array 
np.sum(stats)

21

In [48]:
#Adds up values vertically 
np.sum(stats, axis=0)

array([5, 7, 9])

Reorganizing Arrays

In [49]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [50]:
#change shape to an 8 by 1 
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [53]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [55]:
#Vertically stacking vectors 
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Miscellaneous

Load Data 

In [57]:
#filedata = np.genfromtxt('data.txt', delimiter=',')
#filedata

In [59]:
filedata = np.random.randint(24, size =(5,5))
filedata

array([[ 5,  6, 13, 11, 10],
       [12, 16, 10, 15, 15],
       [13, 23,  4, 21, 13],
       [ 5, 12,  0,  7,  8],
       [ 6, 20,  5, 22, 22]])

Boolean Masking and Advanced Indexing 

In [61]:
filedata[filedata > 12]

array([13, 16, 15, 15, 13, 23, 21, 13, 20, 22, 22])

In [62]:
filedata > 12

array([[False, False,  True, False, False],
       [False,  True, False,  True,  True],
       [ True,  True, False,  True,  True],
       [False, False, False, False, False],
       [False,  True, False,  True,  True]])

In [63]:
#You can index with a list in NumPY 
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [64]:
((filedata > 10) & (filedata < 15))

array([[False, False,  True,  True, False],
       [ True, False, False, False, False],
       [ True, False, False, False,  True],
       [False,  True, False, False, False],
       [False, False, False, False, False]])

In [65]:
#not
(~(filedata > 10) & (filedata < 15))

array([[ True,  True, False, False,  True],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [ True, False,  True,  True,  True],
       [ True, False,  True, False, False]])