# Numpy Exercises

In [6]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [5]:
import numpy as np 

1. How many negative numbers are there?

In [8]:
a[a<0].size

4

2. How many positive numbers are there?

In [9]:
a[a>0].size

5

3. How many even positive numbers are there?

In [85]:
pos_even = a[(a > 0) & (a%2==0)]
print(pos_even)

[ 4 10 12]


4. If you were to add 3 to each data point, how many positive numbers would there be?

In [13]:
add_three = a + 3
add_three[add_three > 0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [12]:
add_three[add_three > 0].size

10

5. If you squared each number, what would the new mean and standard deviation be?



In [71]:
array_squared =[n * n for n in a]
print(array_squared)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [72]:
print(np.mean(array_squared))

38.5


In [73]:
print(np.std(array_squared))

32.41990129534635


6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.



In [14]:
centered = a - a.mean()
centered


array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [15]:
centered.mean()

0.0

7. Calculate the z-score for each data point. Recall that the z-score is given by:



In [89]:
from scipy import stats

In [90]:
stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.



### SETUP1

In [18]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = np.array(a)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list


In [19]:
sum_of_a = a.sum()
sum_of_a

55

### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list


In [20]:
min_of_a = a.min()
min_of_a

1

### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list


In [21]:
max_of_a = a.max(axis=0)
max_of_a

10

### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list


In [22]:
mean_of_a = a.mean()
mean_of_a

5.5

### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together


In [23]:
product_of_a = 1
for n in a:
    product_of_a = product_of_a * n 
    
product_of_a

3628800

### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]


In [24]:
squares_of_a = [n ** 2 for n in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers


In [25]:
odds_in_a = [n for n in a if n % 2 != 0]
odds_in_a

[1, 3, 5, 7, 9]

### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.


In [26]:
evens_in_a = [n for n in a if n % 2 == 0]
evens_in_a

[2, 4, 6, 8, 10]

## SETUP 2

Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [27]:
b = [[3, 4, 5],[6, 7, 8]]
b = np.array(b)
print(b)

[[3 4 5]
 [6 7 8]]


https://towardsdatascience.com/a-visual-guide-to-multidimensional-numpy-array-aggregation-97a8960b3c59

When using aggregation commands in 2 dimensional arrays, you must specify which axis you want to collapse. What you would think intuitively would happen usually happens when you choose axis=0.

### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**


In [147]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
print(sum_of_b)

33


In [ ]:
flattened_list = 0 
for numbers in b: 
    for n in numbers: 
        flattened_list.append(n)
return flattened_list 

In [28]:
np.sum(b)

33

### Exercise 2 - refactor the following to use numpy. 


In [29]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  
print(min_of_b)

3


In [30]:
np.min(b)

3

### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.


In [31]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
print(max_of_b)

8


In [32]:
np.max(b)

8

### Exercise 4 - refactor the following using numpy to find the mean of b


In [33]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
print(mean_of_b)

5.5


In [34]:
np.mean(b)

5.5

### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.


In [35]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
print(product_of_b)

20160


In [36]:
np.prod(b)

20160

### Exercise 6 - refactor the following to use numpy to find the list of squares 

In [37]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
print(squares_of_b)

[9, 16, 25, 36, 49, 64]


In [38]:
np.square(b)

array([[ 9, 16, 25],
       [36, 49, 64]])

### Exercise 7 - refactor using numpy to determine the odds_in_b

In [39]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
print(odds_in_b)

[3, 5, 7]


In [40]:
b[b%2 ==1]

array([3, 5, 7])

### Exercise 8 - refactor the following to use numpy to filter only the even numbers


In [41]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
print(evens_in_b)

[4, 6, 8]


In [42]:
b[b%2 == 0]

array([4, 6, 8])

### Exercise 9 - print out the shape of the array b.

In [96]:
b.shape

(2, 3)

### Exercise 10 - transpose the array b.


In [97]:
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

### Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)


In [98]:
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

### Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)


In [99]:
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

## SETUP 3

In [62]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
c = np.array(c)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Exercise 1 - Find the min, max, sum, and product of c.

In [109]:
min_c = np.min(c)
print(min_c)
max_c = np.max(c)
print(max_c)
sum_c = sum(c)
print(sum_c)
print(np.prod(c))

1
9
[12 15 18]
362880


### Exercise 2 - Determine the standard deviation of c.


In [111]:
print(np.std(c))

2.581988897471611


### Exercise 3 - Determine the variance of c.


In [128]:
np.var(c)

6.666666666666667

### Exercise 4 - Print out the shape of the array c


In [100]:
c.shape

(3, 3)

### Exercise 5 - Transpose c and print out transposed result.


In [101]:
np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Exercise 6 - Get the dot product of the array c with c. 


In [113]:
print(c.dot(c))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


### Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261


In [114]:
np.add((c), (np.transpose(c)))

array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

### Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.


In [115]:
np.multiply((c), (np.transpose(c)))

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

## SETUP 4

In [44]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d = np.array(d)
print(d)

[[ 90  30  45   0 120 180]
 [ 45 -90 -30 270  90   0]
 [ 60  45 -45  90 -45 180]]


### Exercise 1 - Find the sine of all the numbers in d


In [116]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

### Exercise 2 - Find the cosine of all the numbers in d


In [117]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

### Exercise 3 - Find the tangent of all the numbers in d


In [125]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

### Exercise 4 - Find all the negative numbers in d

In [122]:
neg_d = d[d<0]
print(neg_d)

[-90 -30 -45 -45]


### Exercise 5 - Find all the positive numbers in d


In [123]:
pos_d = d[d>0]
print(pos_d)

[ 90  30  45 120 180  45 270  90  60  45  90 180]


### Exercise 6 - Return an array of only the unique numbers in d.


In [126]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

### Exercise 7 - Determine how many unique numbers there are in d.


In [45]:
np.unique(d).size

11

### Exercise 8 - Print out the shape of d.


In [46]:
d.shape

(3, 6)

### Exercise 9 - Transpose and then print out the shape of d.


In [47]:
np.transpose(d)

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

### Exercise 10 - Reshape d into an array of 9 x 2


In [121]:
d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])